artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/nsrawat009/Text-Summarizer-project/raw/main/samsumdata.zip
  local_data_file: artifacts/data_ingestion/samsumdata.zip
  unzip_dir: artifacts/data_ingestion


